// src/js/prep.js

// Calculate tomorrow's date by default
let prepFilterDate = new Date();
prepFilterDate.setDate(prepFilterDate.getDate() + 1);
let prepDateStr = prepFilterDate.toISOString().split("T")[0];

function rPrep(overrideDate = null) {
  if (overrideDate) prepDateStr = overrideDate;
  document.getElementById("prep-date-picker").value = prepDateStr;

  let itemTotals = {};

  // 1. Find all orders for the target date that haven't been cancelled
  const activeOrders = orders.filter(
    (o) => o.date === prepDateStr && o.status !== "Cancelled",
  );

  // 2. Loop through every item in every order and aggregate the math
  activeOrders.forEach((o) => {
    (o.items || []).forEach((it) => {
      let name = it.name.trim();
      let qty = parseFloat(it.qty) || 0;

      if (itemTotals[name]) {
        itemTotals[name] += qty;
      } else {
        itemTotals[name] = qty;
      }
    });
  });

  // 3. Render the aggregated table
  const tb = document.getElementById("prep-tbody");
  const itemNames = Object.keys(itemTotals).sort();

  if (itemNames.length === 0) {
    tb.innerHTML = `<tr><td colspan="2" style="text-align: center; padding: 40px; color: var(--tx-3);">No items scheduled for production on this date.</td></tr>`;
    return;
  }

  tb.innerHTML = itemNames
    .map((name) => {
      return `
        <tr style="border-bottom: 1px solid var(--bd);">
            <td style="font-weight: bold; color: var(--tx-1); font-size: 15px;">${name}</td>
            <td style="text-align: right; font-weight: bold; color: var(--accent); font-size: 16px;">${itemTotals[name]}</td>
        </tr>`;
    })
    .join("");
}

// --- Print function specifically for the Halwais/Kitchen ---
function printPrepList() {
  const activeOrders = orders.filter(
    (o) => o.date === prepDateStr && o.status !== "Cancelled",
  );
  if (activeOrders.length === 0)
    return customAlert("Nothing to print for this date.");

  let itemTotals = {};
  activeOrders.forEach((o) => {
    (o.items || []).forEach((it) => {
      let name = it.name.trim();
      let qty = parseFloat(it.qty) || 0;
      if (itemTotals[name]) itemTotals[name] += qty;
      else itemTotals[name] = qty;
    });
  });

  const itemNames = Object.keys(itemTotals).sort();
  let rows = itemNames
    .map(
      (name) => `
        <tr>
            <td style="padding: 12px; border-bottom: 1px solid #ccc; font-size: 18px; font-weight: bold;">${name}</td>
            <td style="padding: 12px; border-bottom: 1px solid #ccc; text-align: right; font-size: 20px; font-weight: bold;">${itemTotals[name]}</td>
        </tr>
    `,
    )
    .join("");

  const printHTML = `
    <html>
    <head>
        <title>Prep List - ${fd(prepDateStr)}</title>
        <style>
            body { font-family: sans-serif; color: #000; padding: 20px; max-width: 600px; margin: 0 auto; }
            h1 { text-align: center; border-bottom: 3px solid #000; padding-bottom: 10px; margin-bottom: 30px; text-transform: uppercase; }
            table { width: 100%; border-collapse: collapse; }
            th { background: #eee; padding: 12px; text-align: left; font-size: 14px; text-transform: uppercase; }
        </style>
    </head>
    <body>
        <h1>Kitchen Prep List</h1>
        <div style="font-size: 18px; margin-bottom: 20px;"><b>For Delivery On:</b> ${fd(prepDateStr)}</div>
        <table>
            <thead><tr><th>Item to Prepare</th><th style="text-align: right;">Total Qty Needed</th></tr></thead>
            <tbody>${rows}</tbody>
        </table>
        <div style="margin-top: 40px; font-size: 12px; color: #666; text-align: center;">Generated by Gilhotra Sweets POS</div>
    </body>
    </html>`;

  const w = window.open("", "_blank");
  w.document.write(printHTML);
  w.document.close();
  setTimeout(() => w.print(), 250);
}
